apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: y0406nibr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: y0406nibr-go 
  name: y0406nibr-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: y0406nibr-go 
